name: markdown-to-confluence-sync
description: This syncs a given directory or single file as child page(s) to a Confluence parent ID page.
branding:
  icon: upload-cloud
  color: green
inputs:
  cloud:
    description: the Confluence cloud instance name
    required: true
  user:
    description: the user with sufficient privileges to create pages
    required: true
  token:
    description: user token
    required: true
  parent_page_id:
    description: the page ID of the parent page. The childpages will appear under this page.
    required: true
  space_key:
    description: the Confluence space key
    required: true
  input_directory:
    description: the directory where the markdown files to sync
    required: false
  input_file:
    description: the location of the markdown file to sync
    required: false
  exclude_files:
    description: markdown files to exclude from syncing
    required: false
  full_width:
    description: create Confluence page in full-width
    required: false
outputs:
  links:
    description: title and link of uploaded or updated page(s)
runs:
  using: docker
  image: Dockerfile